name = "JordanForm"
uuid = "3e0f3a26-b485-4542-9924-3b1a11022d22"
authors = ["Frederik Baymler Mathiesen"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
